config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "team.kafeem" do
    scope module: :admin do
      resource :session, only: [:create, :destroy]
      put 'toggle_accepting_orders', to: 'admins#toggle_accepting_orders'

      resources :orders, only: :index do
        member do
          patch "receive", to: "orders#receive"
          patch "prepare", to: "orders#prepare"
          patch "deliver", to: "orders#deliver"
          patch "cancel", to: "orders#cancel"
        end
      end

      resources :categories
      resources :products, except: [:index, :destroy] do
        member do
          put "availability", to: "products#toggle_availability"
        end
      end

      resource :balance, only: :show do
        get ":cid/add-tokens", to: "balances#add_tokens", as: :add_tokens
        put ":cid/update", to: "balances#update", as: :update_customer
      end

      get "settings", to: "pages#settings"
      get "login", to: "pages#login", as: :team_login

      get "/", to: "orders#index"
    end
  end

  constraints subdomain: "kafeem" do
    get "welcome/download"
    get "welcome/customer"
    get "welcome/permissions"

    get "app", to: "pages#app"
    get "tokens", to: "pages#tokens"

    resources :order_items, only: [:new, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :edit, :update] do
      member do
        patch "finalize", to: "orders#finalize"
      end
    end

    resources :customers, only: [:create]
    post "push_subscriptions", to: "push_subscriptions#create"
    get 'tv', to: 'pages#tv'
    
    get "/", to: "pages#home"
  end
  
  get "manifest" => "pwa#manifest", :as => :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#mrshq"
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :name, with: ->(e) { e.strip.downcase }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  private

  def generate_uuid_v7
    self.id ||= SecureRandom.uuid_v7
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :title, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :admin, to: :session, allow_nil: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # self.primary_key = "id"

  after_update_commit -> { broadcast_update_to :balance, target: "balance-#{id}", html: balance }

  before_create :generate_uuid_v7
  validates :name, presence: true

  has_one :push_subscription, dependent: :delete
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  before_create :generate_code

  after_update_commit :broadcast_changes_to_admins
  after_update_commit :broadcast_changes_to_customer
  after_update_commit :broadcast_changes_to_tv

  scope :in_progress, -> { where(state: %w[finalized received prepared]) }
  scope :done, -> { where(state: %w[delivered cancelled]) }

  enum :state, {
    open: 0,
    finalized: 1,
    received: 2,
    prepared: 3,
    delivered: 4,
    cancelled: 5
  }

  def available_order_items
    order_items
      .joins(:product)
      .where(product: { is_available: true })
      .order(:created_at)
  end

  def unavailable_order_items
    order_items
      .joins(:product)
      .where(product: { is_available: false })
      .order(:created_at)
  end

  def total_sum
    order_items.sum { |order_item| order_item.amount * order_item.cost }
  end

  private

  def generate_code
    self.code = ('0'..'9').to_a.shuffle.first(4).join('')
  end

  def broadcast_changes_to_customer
    return unless saved_change_to_state?

    broadcast_update_to :order, partial: "orders/states/#{state}"
    broadcast_replace_to :customer_orders
  end

  def broadcast_changes_to_admins
    case state.to_sym
    when :finalized
      broadcast_append_to :orders, partial: 'admin/orders/order'
    when :received, :prepared
      broadcast_replace_to :orders, partial: 'admin/orders/order'
    when :cancelled, :delivered
      broadcast_remove_to :orders
    end
  end

  def broadcast_changes_to_tv
    case state.to_sym
    when :received
      broadcast_append_to :tv_orders, target: 'orders-received', partial: 'pages/tv/order_number', locals: { id:, state: }
    when :prepared
      broadcast_append_to :tv_orders, target: 'orders-prepared', partial: 'pages/tv/order_number', locals: { id:, state: }
      broadcast_remove_to :tv_orders, target: "order-number-#{id}-received"
    when :delivered
      broadcast_remove_to :tv_orders, target: "order-number-#{id}-prepared"
    when :cancelled
      broadcast_remove_to :tv_orders, target: "order-number-#{id}-received"
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :amount, :cost, presence: true
  validates :amount, :cost, numericality: {
    only_integer: true, greater_than_or_equal_to: 1
  }

  def total
    amount * cost
  end
end

app/models/product.rb
class Product < ApplicationRecord
  MINIMAL_PRICE = 1
  THUMBNAIL_DIMENSION = 96 * 3

  belongs_to :category

  has_one_attached :image do |image|
    image.variant :thumbnail, resize_to_fill: [THUMBNAIL_DIMENSION, THUMBNAIL_DIMENSION], preprocessed: true
    image.variant :modal, resize_to_fill: [900, 600], preprocessed: true
  end

  validates :title, presence: true
  validates :price, numericality: { 
    only_integer: true, greater_than_or_equal_to: MINIMAL_PRICE 
  }

  scope :available, -> { where(is_available: true) }
end

app/models/push_subscription.rb
class PushSubscription < ApplicationRecord
  validates :endpoint, :p256dh, :auth, presence: true

  belongs_to :customer
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :admin
end

app/controllers/pwa_controller.rb
class PwaController < ApplicationController
  def manifest
    if request.subdomain.include? 'team'
      @name = 'Kaféem Admin'
      @root = '/orders'
    else
      @name = 'Kaféem'
      @root = '/app'
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/components_helper.rb
require "tailwind_merge"

module ComponentsHelper
  def tw(*classes)
    TailwindMerge::Merger.new.merge(classes.join(" "))
  end

  PRIMARY_CLASSES = " bg-primary text-primary-foreground hover:bg-primary/80 "
  SECONDARY_CLASSES = " bg-secondary text-secondary-foreground hover:bg-secondary/80 "
  OUTLINE_CLASSES = "  border border-input bg-background hover:bg-accent hover:text-accent-foreground "
  GHOST_CLASSES = " hover:bg-accent hover:text-accent-foreground  "
  DESTRUCTIVE_CLASSES = " bg-destructive text-destructive-foreground hover:bg-destructive/90 "

  module Button
    PRIMARY = ComponentsHelper::PRIMARY_CLASSES
    SECONDARY = ComponentsHelper::SECONDARY_CLASSES
    OUTLINE = ComponentsHelper::OUTLINE_CLASSES
    GHOST = ComponentsHelper::GHOST_CLASSES
    DESTRUCTIVE = ComponentsHelper::DESTRUCTIVE_CLASSES
  end

  module Alert
  end
end

app/helpers/menu_helper.rb
module MenuHelper
  def cafe_tab_active
    ["categories", "products"].include?(controller_name) ? "text-zinc-700" : "text-zinc-400"
  end

  def customer_cafe_tab_active
    action_name == "app" ? "text-zinc-700" : "text-zinc-400"
  end

  def orders_tab_active
    controller_name == "orders" ? "text-zinc-700" : "text-zinc-400"
  end

  def balance_tab_active
    controller_name == "balances" ? "text-zinc-700" : "text-zinc-400"
  end

  def settings_tab_active
    action_name == "settings" ? "text-zinc-700" : "text-zinc-400"
  end

  def tokens_tab_active
    action_name == "tokens" ? "text-zinc-700" : "text-zinc-400"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def in_progress_tab_class
    return 'bg-white border border-zinc-200' if params[:state] == 'done'

    'bg-zinc-950 text-white border border-zinc-900'
  end

  def done_tab_class
    return 'bg-zinc-950 text-white border border-zinc-900' if params[:state] == 'done'

    'bg-white border border-zinc-200'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def humanized_price(amount)
    case amount
    when 1
      '1 žetón'
    when 2..4
      "#{amount} žetóny"
    else
      "#{amount} žetónov"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/admins/toggle_accepting_orders.turbo_stream.erb
<%= turbo_stream.replace 'accepting-orders-switch' do %>
  <div id='accepting-orders-switch' data-controller='accepting-orders'>
    <%= render_switch '', id: 'available', name: 'available', checked: Current.admin.accepting_orders, action_on_toggle: 'accepting-orders#toggle' %>
  </div>
<% end %>

app/views/admin/pages/login.html.erb
<div class='fixed inset-0'>
  <div class='px-8 h-screen flex flex-col justify-center items-center'>
    <h1 class="text-4xl tracking-tighter font-semibold">
      kaféem tím
    </h1>
    <%= form_with url: session_url, class: "mt-6 space-y-4" do |f| %>
      <div class='w-full'>
        <%= f.label :name, 'Prihlasovacie meno', class: 'block text-zinc-700 font-medium' %>
        <%= f.text_field :name, required: true, autofocus: true, autocomplete: :username, value: params[:name], class: 'rounded-lg mt-2 bg-zinc-100 border border-zinc-300 px-5 py-2.5 w-full focus:ring-0 focus:border-blue-300 focus:bg-zinc-50 transition duration-150' %>
      </div>

      <div class='w-full'>
        <%= f.label :password, 'Heslo', class: 'block text-zinc-700 font-medium' %>
        <%= f.password_field :password, required: true, autocomplete: "current-password", maxlength: 72, class: 'rounded-lg mt-2 bg-zinc-100 border border-zinc-300 px-5 py-2.5 w-full focus:ring-0 focus:border-blue-300 focus:bg-zinc-50 transition duration-150' %>
      </div>

      <div>
        <%= f.submit 'Prihlásiť', class: 'mt-6 w-full text-center py-4 rounded-xl bg-blue-500 cursor-pointer hover:bg-blue-400 text-zinc-50 font-semibold transition' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/pages/settings.html.erb
<% content_for :title, 'Nastavenia' %>
<% content_for :action do %>
  <%= button_to session_path, method: :delete, class: 'inline-block ml-4 text-xl transition text-rose-500 hover:text-rose-200' do %>
    <%= icon('fa-solid', 'right-from-bracket') %>
  <% end %>
<% end %>

<div class='text-lg'>
  <div class='pb-4 flex justify-between items-center'>
    <div class='font-semibold'>
      Prijímať nové objednávky?
    </div>
    <div id='accepting-orders-switch' data-controller='accepting-orders'>
      <%= render_switch '', id: 'available', name: 'available', checked: Current.admin.accepting_orders, action_on_toggle: 'accepting-orders#toggle' %>
    </div>
  </div>
</div>

app/views/layouts/admin/_header.html.erb
<header class='z-20 fixed top-0 left-0 right-0 bg-zinc-50 h-16 px-5 shadow-lg shadow-zinc-400/10'>
  <div class='flex justify-between items-center h-16'>
    <div>
      <%= yield :back %>
    </div>
    <h1 class='absolute left-1/2 -translate-x-1/2 font-semibold text-xl'>
      <%= yield :title %>
    </h1>
    <div>
      <%= yield :action %>
    </div>
  </div>
</header>

app/views/layouts/admin/_menu.html.erb
<div class='z-30 bg-zinc-50 fixed bottom-0 left-0 right-0 pt-2 px-4 pb-6 border-t border-zinc-200 flex justify-evenly items-center'>
  <%= link_to orders_path, class: "w-20 flex flex-col justify-center items-center #{orders_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'receipt', class: 'text-xl' %>
    <div class='text-sm'>
      Objednávky
    </div>
  <% end %>

  <%= link_to categories_path, class: "w-20 flex flex-col justify-center items-center #{cafe_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'hotdog', class: 'text-xl' %>
    <div class='text-sm'>
      Produkty
    </div>
  <% end %>

  <%= link_to balance_path, class: "w-20 flex flex-col justify-center items-center #{balance_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'coins', class: 'text-xl' %>
    <div class='text-sm'>
      Žetóny
    </div>
  <% end %>

  <%= link_to settings_path, class: "w-16 flex flex-col justify-center items-center #{settings_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'bars', class: 'text-xl' %>
    <div class='text-sm'>
      Účet
    </div>
  <% end %>
</div>

app/views/layouts/shared/_alert.html.erb
<% if alert %>
  <div class='gap-3 z-40 fixed top-20 left-4 right-4'>
    <div
      data-controller="notification"
      data-notification-delay-value="4000"
      class="transition transform duration-500 hidden"
      data-transition-enter-from="opacity-0 -translate-y-12"
      data-transition-enter-to="opacity-100 translate-y-0"
      data-transition-leave-from="opacity-100 translate-y-0"
      data-transition-leave-to="opacity-0 -translate-y-12"
    >
      <div class='px-4 py-2.5 bg-rose-100 border border-rose-200 text-rose-500 rounded-xl flex justify-between items-start'>
        <div><%= alert%></div>
        <button data-action="notification#hide">
          <%= icon 'fa-solid', 'xmark' %>
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/shared/_menu.html.erb
<div class='fixed bottom-0 left-0 right-0 pt-2 px-4 pb-6 border-t border-zinc-200 flex justify-evenly items-center'>
  <%= link_to admin_orders_path, class: "w-20 flex flex-col justify-center items-center #{orders_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'receipt', class: 'text-xl' %>
    <div class='text-sm'>
      Objednávky
    </div>
  <% end %>

  <%= link_to categories_path, class: "w-20 flex flex-col justify-center items-center #{cafe_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'hotdog', class: 'text-xl' %>
    <div class='text-sm'>
      Produkty
    </div>
  <% end %>

  <%= link_to balance_path, class: "w-20 flex flex-col justify-center items-center #{balance_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'coins', class: 'text-xl' %>
    <div class='text-sm'>
      Žetóny
    </div>
  <% end %>

  <%= link_to account_path, class: "w-16 flex flex-col justify-center items-center #{account_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'bars', class: 'text-xl' %>
    <div class='text-sm'>
      Účet
    </div>
  <% end %>
</div>

app/views/layouts/shared/_notice.html.erb
<% if notice %>
  <div class='gap-3 z-40 fixed top-20 left-4 right-4'>
    <div
      data-controller="notification"
      data-notification-delay-value="3000"
      class="transition transform duration-500 hidden"
      data-transition-enter-from="opacity-0 -translate-y-12"
      data-transition-enter-to="opacity-100 translate-y-0"
      data-transition-leave-from="opacity-100 translate-y-0"
      data-transition-leave-to="opacity-0 -translate-y-12"
    >
      <div class='px-4 py-2.5 bg-green-100 border border-green-200 text-green-500 rounded-xl flex justify-between items-start'>
        <div><%= notice%></div>
        <button data-action="notification#hide">
          <%= icon 'fa-solid', 'xmark' %>
        </button>
      </div>
    </div>
  </div>
<% end %>