config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "team.kafeem" do
    scope module: :admin do
      resource :session, only: [:create, :destroy]
      put 'toggle_accepting_orders', to: 'admins#toggle_accepting_orders'

      resources :orders, only: :index do
        member do
          patch "receive", to: "orders#receive"
          patch "prepare", to: "orders#prepare"
          patch "deliver", to: "orders#deliver"
          patch "cancel", to: "orders#cancel"
        end
      end

      resources :categories
      resources :products, except: [:index, :destroy] do
        member do
          put "availability", to: "products#toggle_availability"
        end
      end

      resource :balance, only: :show do
        get ":cid/add-tokens", to: "balances#add_tokens", as: :add_tokens
        put ":cid/update", to: "balances#update", as: :update_customer
      end

      get "settings", to: "pages#settings"
      get "login", to: "pages#login", as: :team_login

      get "/", to: "orders#index"
    end
  end

  constraints subdomain: "kafeem" do
    get "welcome/download"
    get "welcome/customer"
    get "welcome/permissions"

    get "app", to: "pages#app"
    get "tokens", to: "pages#tokens"

    resources :order_items, only: [:new, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :edit, :update] do
      member do
        patch "finalize", to: "orders#finalize"
      end
    end

    resources :customers, only: [:create]
    post "push_subscriptions", to: "push_subscriptions#create"
    get 'tv', to: 'pages#tv'
    
    get "/", to: "pages#home"
  end
  
  get "manifest" => "pwa#manifest", :as => :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#mrshq"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  before_create :generate_code

  after_update_commit :broadcast_changes_to_admins
  after_update_commit :broadcast_changes_to_customer
  after_update_commit :broadcast_changes_to_tv

  scope :in_progress, -> { where(state: %w[finalized received prepared]) }
  scope :done, -> { where(state: %w[delivered cancelled]) }

  enum :state, {
    open: 0,
    finalized: 1,
    received: 2,
    prepared: 3,
    delivered: 4,
    cancelled: 5
  }

  def available_order_items
    order_items
      .joins(:product)
      .where(product: { is_available: true })
      .order(:created_at)
  end

  def unavailable_order_items
    order_items
      .joins(:product)
      .where(product: { is_available: false })
      .order(:created_at)
  end

  def total_sum
    order_items.sum { |order_item| order_item.amount * order_item.cost }
  end

  private

  def generate_code
    self.code = ('0'..'9').to_a.shuffle.first(4).join('')
  end

  def broadcast_changes_to_customer
    return unless saved_change_to_state?

    broadcast_update_to :order, partial: "orders/states/#{state}"
    broadcast_replace_to :customer_orders
  end

  def broadcast_changes_to_admins
    case state.to_sym
    when :finalized
      broadcast_append_to :orders, partial: 'admin/orders/order'
    when :received, :prepared
      broadcast_replace_to :orders, partial: 'admin/orders/order'
    when :cancelled, :delivered
      broadcast_remove_to :orders
    end
  end

  def broadcast_changes_to_tv
    case state.to_sym
    when :received
      broadcast_append_to :tv_orders, target: 'orders-received', partial: 'pages/tv/order_number', locals: { id:, state: }
    when :prepared
      broadcast_append_to :tv_orders, target: 'orders-prepared', partial: 'pages/tv/order_number', locals: { id:, state: }
      broadcast_remove_to :tv_orders, target: "order-number-#{id}-received"
    when :delivered
      broadcast_remove_to :tv_orders, target: "order-number-#{id}-prepared"
    when :cancelled
      broadcast_remove_to :tv_orders, target: "order-number-#{id}-received"
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, except: :index

  def index
    @orders = Order.done.order(created_at: :desc)
    return @orders if params[:state] == 'done'

    @orders = Order.in_progress.order(:created_at)
  end

  def receive
    return unless @order.finalized?

    @order.received!
  end

  def prepare
    return unless @order.received?

    @order.prepared!
    PushService.send_notification(
      push_subscription: @order.customer.push_subscription,
      title: "Objednávka ##{@order.id} je hotová! 📣",
      body: "Pri vyzdvihnutí budeš potrebovať kód: #{@order.code}.",
    ) if @order.customer.push_subscription
  end

  def deliver
    return unless @order.prepared!

    @order.delivered!
  end

  def cancel
    return unless @order.finalized? || @order.received?

    service = CustomerOrderService.new(customer: @order.customer, order: @order)

    service.cancel_order!
    PushService.send_notification(
      push_subscription: @order.customer.push_subscription,
      title: "Objednávka ##{@order.id} je zrušená. ❌", 
      body: "Asi nám práve niečo došlo. Radi ti však pripravíme to, čo máme.",
    )
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout "app"

  before_action :set_order, except: :index
  before_action :authorize_check, except: :index

  def index
    @orders = current_customer.orders.includes(:order_items).order(created_at: :desc)
  end

  def show
    set_order_items
  end

  def edit
  end

  def update
    @order.update!(note: params[:order][:note])
  end

  def finalize
    return unless @order.open?

    service = CustomerOrderService.new(customer: current_customer, order: @order)

    if service.not_accepting_new_orders?
      set_order_items
      
      flash.now[:alert] = 'Kaféem momentálne neprijíma nové objednávky.'
      return render :show, status: :unprocessable_entity
    end

    if service.any_order_item_unavailable?
      service.remove_unavailable_order_items
      set_order_items

      flash.now[:alert] = 'To bolo tesné! Niektorý z našich produktov už, žiaľ, nie je dostupný.'
      return render :show, status: :unprocessable_entity
    end

    if service.empty_order?
      set_order_items

      flash.now[:alert] = 'Objednávka je prázdna.'
      return render :show, status: :unprocessable_entity
    end

    if service.any_product_price_has_changed?
      service.update_order_items_with_changed_product_price!
      set_order_items

      flash.now[:alert] = 'Niektorý z produktov, ktoré máš v objednávke, zmenil svoju cenu. Pred potvrdením objednávky si to pre istotu skontroluj.'
      return render :show, status: :unprocessable_entity
    end

    if service.sufficient_balance?
      service.pay!
    else
      flash.now[:alert] = 'Na túto objednávku nemáš dostatok žetónov.'
      set_order_items

      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def set_order_items
    @order_items = @order.order_items
  end

  def authorize_check
    return if @order.customer == current_customer 

    redirect_to app_url, alert: '"...čo ťa do toho?" (Ján 21:22)'
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def in_progress_tab_class
    return 'bg-white border border-zinc-200' if params[:state] == 'done'

    'bg-zinc-950 text-white border border-zinc-900'
  end

  def done_tab_class
    return 'bg-zinc-950 text-white border border-zinc-900' if params[:state] == 'done'

    'bg-white border border-zinc-200'
  end
end

app/views/admin/orders/_actions.html.erb
<div id='actions' class='flex justify-between items-center gap-4'>
  <% case order.state.to_sym %>
  <% when :finalized %>
    <%= button_to cancel_order_path(order), method: :patch, form_class: 'w-full group', class: 'w-full py-3 bg-rose-500 group-aria-busy:bg-rose-300 text-rose-50 rounded-xl font-medium text-lg text-center' do %>
      <div class='group-aria-busy:hidden'>
        Odmietnuť
      </div>
      <div class='hidden group-aria-busy:block animate-spin'>
        <%= icon 'fa-solid', 'spinner' %>
      </div>
    <% end %>
    <%= button_to receive_order_path(order), method: :patch, form_class: 'w-full group', class: 'w-full py-3 bg-blue-500 group-aria-busy:bg-blue-300 text-blue-50 rounded-xl font-medium text-lg text-center' do %>
      <div class='group-aria-busy:hidden'>
        Prijať
      </div>
      <div class='hidden group-aria-busy:block animate-spin'>
        <%= icon 'fa-solid', 'spinner' %>
      </div>
    <% end %>
  <% when :received %>
    <%= button_to cancel_order_path(order), method: :patch, form_class: 'group', class: 'px-5 py-3 bg-rose-500 group-aria-busy:bg-rose-300 text-rose-50 rounded-xl font-medium text-lg text-center' do %>
      <div class='group-aria-busy:hidden'>
        <%= icon 'fa-solid', 'xmark' %>
      </div>
      <div class='hidden group-aria-busy:block animate-spin'>
        <%= icon 'fa-solid', 'spinner' %>
      </div>
    <% end %>
    <%= button_to prepare_order_path(order), method: :patch, form_class: 'w-full group', class: 'w-full py-3 bg-sky-500 group-aria-busy:bg-sky-300 text-sky-50 rounded-xl font-medium text-lg text-center' do %>
      <div class='group-aria-busy:hidden'>
        Je pripravená!
      </div>
      <div class='hidden group-aria-busy:block animate-spin'>
        <%= icon 'fa-solid', 'spinner' %>
      </div>
    <% end %>
  <% when :prepared %>
    <%= button_to deliver_order_path(order), method: :patch, form_class: 'w-full group', class: 'w-full py-3 bg-green-400 group-aria-busy:bg-green-300 text-green-50 rounded-xl font-medium text-lg text-center' do %>
      <div class='group-aria-busy:hidden'>
        Odovzdať
      </div>
      <div class='hidden group-aria-busy:block animate-spin'>
        <%= icon 'fa-solid', 'spinner' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admin/orders/_badge.html.erb
<div id='badge'>
  <% case order.state.to_sym %>
  <% when :finalized %>
    <div class='px-3 py-1 rounded-2xl bg-zinc-400 text-orange-50'>
      Nová
    </div>
  <% when :received %>
    <div class='px-3 py-1 rounded-2xl bg-blue-500 text-blue-50'>
      Prijatá
    </div>
  <% when :prepared %>
    <div class='px-3 py-1 rounded-2xl bg-sky-500 text-sky-50'>
      Pripravená
    </div>
  <% when :delivered %>
    <div class='px-3 py-1 rounded-2xl bg-green-400 text-green-50'>
      Odovzdaná
    </div>
  <% when :cancelled %>
    <div class='px-3 py-1 rounded-2xl bg-rose-500 text-rose-50'>
      Odmietnutá
    </div>
  <% end %>
</div>

app/views/admin/orders/_order.html.erb
<div id='<%= dom_id order %>' class='bg-white shadow-lg shadow-zinc-200 border border-zinc-200 rounded-xl p-4'>
  <div class='flex justify-between items-center relative'>
    <h3 class='text-2xl font-medium'>#<%= order.id %></h3>
    <%= render 'admin/orders/badge', order: %>
    <% if order.prepared? %>
      <div class='absolute top-0 left-0 right-0 text-center text-2xl font-light'>
        <%= order.code %>
      </div>
    <% end %>
  </div>
  <div class='text-zinc-600 mt-4 mb-2'>
    <ul class='list-disc pl-4'>
      <% order.order_items.each do |order_item| %>
        <li><%= order_item.amount %>x <%= order_item.product.title %></li>
      <% end %>
    </ul>
  </div>
  <% if order.note.present? %>
    <div class='pt-2 border-t border-zinc-200'>
      <strong class='font-semibold'>Poznámka:</strong>
      <%= order.note %>
    </div>
  <% end %>
  <div class='mt-4'>
    <%= render 'admin/orders/actions', order: %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<% content_for :title, 'Objednávky' %>

<% unless params[:state] == 'done' %>
  <%= turbo_stream_from :orders %>
<% end %>

<div class='flex gap-2'>
  <%= link_to url_for({ state: :in_progress }), class: "#{in_progress_tab_class} px-4 py-2.5 rounded-full" do %>
    Prebiehajúce
  <% end %>
  <%= link_to url_for({ state: :done }), class: "#{done_tab_class} px-4 py-2.5 rounded-full" do %>
    Ukončené
  <% end %>
</div>

<div id='orders' class='mt-4 space-y-4 mb-20'>
  <% @orders.each do |order| %>
    <%= render order %>
  <% end %>
</div>