config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "team.kafeem" do
    scope module: :admin do
      resource :session, only: [:create, :destroy]
      put 'toggle_accepting_orders', to: 'admins#toggle_accepting_orders'

      resources :orders, only: :index do
        member do
          patch "receive", to: "orders#receive"
          patch "prepare", to: "orders#prepare"
          patch "deliver", to: "orders#deliver"
          patch "cancel", to: "orders#cancel"
        end
      end

      resources :categories
      resources :products, except: [:index, :destroy] do
        member do
          put "availability", to: "products#toggle_availability"
        end
      end

      resource :balance, only: :show do
        get ":cid/add-tokens", to: "balances#add_tokens", as: :add_tokens
        put ":cid/update", to: "balances#update", as: :update_customer
      end

      get "settings", to: "pages#settings"
      get "login", to: "pages#login", as: :team_login

      get "/", to: "orders#index"
    end
  end

  constraints subdomain: "kafeem" do
    get "welcome/download"
    get "welcome/customer"
    get "welcome/permissions"

    get "app", to: "pages#app"
    get "tokens", to: "pages#tokens"

    resources :order_items, only: [:new, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :edit, :update] do
      member do
        patch "finalize", to: "orders#finalize"
      end
    end

    resources :customers, only: [:create]
    post "push_subscriptions", to: "push_subscriptions#create"
    get 'tv', to: 'pages#tv'
    
    get "/", to: "pages#home"
  end
  
  get "manifest" => "pwa#manifest", :as => :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#mrshq"
end

app/models/customer.rb
class Customer < ApplicationRecord
  # self.primary_key = "id"

  after_update_commit -> { broadcast_update_to :balance, target: "balance-#{id}", html: balance }

  before_create :generate_uuid_v7
  validates :name, presence: true

  has_one :push_subscription, dependent: :delete
  has_many :orders
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      cookies.encrypted.permanent[:cui] = @customer.id

      redirect_to welcome_permissions_url
    else 
      render 'welcome/customer', status: :unprocessable_entity
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name)
  end
end

app/views/layouts/customer/_header.html.erb
<header class='z-20 fixed top-0 left-0 right-0 bg-zinc-50 h-16 px-5 shadow-lg shadow-zinc-400/10'>
  <div class='flex justify-between items-center h-16'>
    <div>
      <%= yield :back %>
    </div>
    <h1 class='absolute left-1/2 -translate-x-1/2 font-semibold text-xl'>
      <%= yield :title %>
    </h1>
    <div class='text-lg'>
      <%= link_to tokens_path do %>
        <%= turbo_stream_from :balance %>
        <div class='font-medium'>
          <span id="balance-<%= current_customer.id %>">
            <%= current_customer.balance %>
          </span>
          <%= icon 'fa-solid', 'coins', class: 'ml-1' %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/customer/_menu.html.erb
<div class='z-30 bg-zinc-50/70 backdrop-blur-lg fixed bottom-0 left-0 right-0 pt-2 pb-6 border-t border-zinc-200 flex justify-evenly items-center'>
  <%= link_to app_path, class: "w-20 flex flex-col justify-center items-center #{customer_cafe_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'hotdog', class: 'text-xl' %>
    <div class='text-sm'>
      Menu
    </div>
  <% end %>

  <%= link_to tokens_path, class: "w-20 flex flex-col justify-center items-center #{tokens_tab_active} transition hover:text-zinc-700 duration-150" do%>
    <%= icon 'fa-solid', 'coins', class: 'text-xl' %>
    <div class='text-sm'>
      Žetóny
    </div>
  <% end %>

    <%= link_to orders_path, class: "w-20 flex flex-col justify-center items-center #{orders_tab_active} transition hover:text-zinc-700 duration-150" do%>
      <%= icon 'fa-solid', 'receipt', class: 'text-xl' %>
      <div class='text-sm'>
        Objednávky
      </div>
    <% end %>
</div>