config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: "team.kafeem" do
    scope module: :admin do
      resource :session, only: [:create, :destroy]
      put 'toggle_accepting_orders', to: 'admins#toggle_accepting_orders'

      resources :orders, only: :index do
        member do
          patch "receive", to: "orders#receive"
          patch "prepare", to: "orders#prepare"
          patch "deliver", to: "orders#deliver"
          patch "cancel", to: "orders#cancel"
        end
      end

      resources :categories
      resources :products, except: [:index, :destroy] do
        member do
          put "availability", to: "products#toggle_availability"
        end
      end

      resource :balance, only: :show do
        get ":cid/add-tokens", to: "balances#add_tokens", as: :add_tokens
        put ":cid/update", to: "balances#update", as: :update_customer
      end

      get "settings", to: "pages#settings"
      get "login", to: "pages#login", as: :team_login

      get "/", to: "orders#index"
    end
  end

  constraints subdomain: "kafeem" do
    get "welcome/download"
    get "welcome/customer"
    get "welcome/permissions"

    get "app", to: "pages#app"
    get "tokens", to: "pages#tokens"

    resources :order_items, only: [:new, :create, :update, :destroy]
    resources :orders, only: [:index, :show, :edit, :update] do
      member do
        patch "finalize", to: "orders#finalize"
      end
    end

    resources :customers, only: [:create]
    post "push_subscriptions", to: "push_subscriptions#create"
    get 'tv', to: 'pages#tv'
    
    get "/", to: "pages#home"
  end
  
  get "manifest" => "pwa#manifest", :as => :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#mrshq"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :title, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Kategória bola vytvorená." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Kategória bola upravená." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [:title])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [:title])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<%= link_to category, class: 'px-4 py-3 bg-zinc-100 border border-zinc-200 rounded-xl flex justify-between items-center' do %>
  <h3 class='text-xl'>
    <%= category.title %>
  </h3>
<% end %>

app/views/admin/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-200/15  text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2>Kategóriu sa nepodarilo uložiť:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title, 'Názov', class: 'block text-zinc-900 font-medium' %>
    <%= f.text_field :title, class: 'rounded-lg mt-2 bg-zinc-100 border border-zinc-300 px-5 py-2.5 w-full focus:ring-0 focus:border-blue-300 focus:bg-zinc-50 transition duration-150' %>
  </div>

  <%= f.submit 'Uložiť', class: 'mt-8 w-full text-center py-4 rounded-xl bg-blue-500 cursor-pointer hover:bg-blue-400 text-zinc-50 font-semibold transition' %>
<% end %>

app/views/admin/categories/edit.html.erb
<% content_for :title, 'Úprava kategórie' %>
<% content_for :back do %>
  <%= link_to @category, class: 'text-sky-500' do %>
    &lt; Späť
  <% end %>
<% end %>

<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<% content_for :title, 'Kategórie produktov' %>
<% content_for :action do %>
  <%= link_to new_category_path, class: 'inline-block ml-4 text-xl transition text-sky-500 hover:text-sky-200' do %>
    <%= icon('fa-solid', 'plus') %>
  <% end %>
<% end %>

<% if @categories.none? %>
  <%= link_to new_category_path do %>
    <div class='p-4 text-zinc-500 border border-dashed border-zinc-600 rounded-xl text-center'>
      Zatiaľ tu žiadna kategória nie je. 
      <br />
      Klikni sem, aby si pridal prvú.
    </div>
  <% end %>
<% end %>


<div id="categories" class='space-y-4'>
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

app/views/admin/categories/new.html.erb
<% content_for :title, 'Nová kategória' %>
<% content_for :back do %>
  <%= link_to categories_path, class: 'text-sky-500' do %>
    &lt; Späť
  <% end %>
<% end %>

<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<% content_for :back do %>
  <%= link_to categories_path, class: 'text-sky-500' do %>
    &lt; Späť
  <% end %>
<% end %>
<% content_for :title, @category.title %>
<% content_for :action do %>
  <%= link_to edit_category_path(@category), class: 'text-xl transition text-sky-500 hover:text-sky-200' do %>
    <%= icon('fa-solid', 'pen-to-square') %>
  <% end %>
  <%= link_to new_product_path(category_id: @category.id), class: 'inline-block ml-4 text-xl transition text-sky-500 hover:text-sky-200' do %>
    <%= icon('fa-solid', 'plus') %>
  <% end %>
<% end %>

<% if @category.products.none? %>
  <%= link_to new_product_path(category_id: @category.id) do %>
    <div class='p-4 text-zinc-500 border border-dashed border-zinc-600 rounded-xl text-center'>
      V tejto kategórii zatiaľ nie je žiadny produkt.
      <br />
      Klikni sem, aby si pridal prvý.
    </div>
  <% end %>
<% end %>

<div class='divide-y divide-zinc-200'>
  <% @category.products.each do |product| %>
    <%= link_to product, class: 'block' do %>
      <%= render 'admin/products/product', product: product %>
    <% end %>
  <% end %>
</div>